# Generated by Django 4.2.3 on 2023-08-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopStore', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
