# Generated by Django 4.2.3 on 2023-08-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopStore', '0008_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='password',
        ),
    ]
