# Generated by Django 4.2.3 on 2023-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopStore', '0009_remove_subscriber_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
