# Generated by Django 4.2.3 on 2023-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopStore', '0010_subscriber_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
